version: '3.1'
services:
  php:
    build:
      context: ./server
    container_name: ${SERVER_NAME}
    ports:
      - ${HTTP_PORT}:80
    restart: always
    volumes:
      - ./:/var/www/html/
      - data_volume:/var/data/recordings
networks:
  default:
    name: ${NETWORK_NAME}
volumes:
  data_volume:
    name: ${DATA_VOLUME}
