* Quick start

Clone this branch

#+begin_src sh :eval never
  git clone --branch package --single-branch git@github.com:abeith/jspsych_auditory_toolbox.git
#+end_src

Build packages (need to run npm install first?)

#+begin_src sh :eval never
  cd packages
  cd plugin-audio-audio-response
  npm run build
  cd ../plugin-av-audio-response
  npm run build
  cd ../plugin-latency-test
  npm run build
  cd ../..
#+end_src

Build and bring up docker-compose configuration

#+begin_src sh :eval never
  docker compose build
  docker compose up -d
#+end_src

Visit examples in browser (e.g. [[http://localhost:8080/examples/jspsych-audio-audio-response.html]])

* plugin-audio-audio-response

** Parameters

- stimulus: Audio file to play
- prompt: Text to display
- trial_duration: Total trial duration in ms

** Description

Stimulus and microphone signal are returned as PCM data. Can be used for latency calculations if stimulus is audible in microphone signal or as a normal audio stim/audio response trial.

* plugin-av-audio-response

** Parameters

- stimulus: Audio file to play
- prompt: Not used
- trial_duration: Total trial duration in ms
- visual_stim: String array of arguments for visual stimulus presentation. Currently if the value is '1' a white box will be displayed, otherwise a black box will be displayed.
- visual_times: Integer array of same length as visual_stim. Determines the times of visual presentation

** Description

Presented for testing only. Current implementation is intended to be used with a barcode like stimulus pair.

* plugin-latency-test
 
** Parameters

- stimulus: Audio file. Must be a 'chirp'
- trial_duration: Total trial duration in ms
- dummy: If false do actual latency test, otherwise simulate one with specified latency in seconds
- f_max: Maximum frequency of chirp
- fft_size: Length of FFT. Should be a power of 2
- vol: Volume to play stimulus at. Use low value for simulations
- random_delay: If true adds a random delay to microphone signal that is then subtracted from latency calculation. Avoids systematic error due to bin alignment.

** Description

Intended use is for participant to hold headphones up to microphone during the trial. This can be repeated in blocks between experiment trials and the calculated latency is then added to the response epoch. Can also be used to measure variability of latency for screening participants.
